from .alg_sieveoferatosthenes import proj_sieve_of_eratosthenes
from .net_portscanner import proj_port_scanner
from .num_bintodec import proj_bin_dec_converter
from .num_changereturn import proj_change_return
from .num_creditcard import proj_cc_validator
from .num_fib import proj_fibonacci
from .num_happynumber import proj_happy_numbers
from .num_pi import proj_pi
from .num_primefactor import proj_prime_factor
from .text_countvowels import proj_count_vowels
from .text_countwords import proj_count_words
from .text_fizzbuzz import proj_fizz_buzz
from .text_palindrome import proj_palindrome_checker
from .text_piglatin import proj_pig_latin
from .text_reversestring import proj_reverse_string
